[project]
name = "data-processor-hive-to-live"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.3.3",
    "pyhive>=0.7.0",
    "sqlalchemy>=2.0.45",
]
